---
#################################
#################################
##      Release to Discord     ##
#################################
#################################

name: Release to Discord

on:
  release:
    types: [published]
jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: LeGitHubDeTai/github-to-discord@main
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
          MESSAGE_COLOR: 2105893
          DISCORD_USERNAME: PrintCFG Release
          DISCORD_AVATAR: https://raw.githubusercontent.com/rootiest/zippy_guides/main/resources/logo.png
          MESSAGE_TITLE: New PrintCFG release!
          MESSAGE_DESCRIPTION: "@PrintCFG Updates"
          FOOTER_TEXT: PrintCFG Klipper Suite
